{% set name = "webtest" %}
{% set version = "3.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7aeab50f970d46c068e7a36dd162cb242591edf72a1d04efd21374772b931741

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - webob >=1.2
    - waitress >=3.0.2
    - beautifulsoup4

test:
  source_files:
    - tests
  imports:
    - webtest
    - webtest.app
    - webtest.compat
    - webtest.debugapp
    - webtest.forms
    - webtest.lint
    - webtest.response
  requires:
    - coverage
    - pastedeploy
    - pyquery
    - wsgiproxy2
    - pytest
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests

about:
  home: https://docs.pylonsproject.org/projects/webtest
  license: MIT
  license_file: license.rst
  license_family: MIT
  summary: helper to test WSGI applications
  description: |
    Webtest tests any application that has a WSGI interface, including an application written
    in a framework that supports WSGI.
  doc_url: https://docs.pylonsproject.org/projects/webtest
  dev_url: https://github.com/Pylons/webtest
